-- Pre-restructure backup 2026-06-07T12:19:27.532814

-- app_config (10 rows)
DELETE FROM "app_config";
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));
INSERT INTO "app_config" ("id", "key", "value") VALUES (, .join(vals));

-- attribute (4 rows)
DELETE FROM "attribute";
INSERT INTO "attribute" ("id", "name", "slug", "type", "image_url", "is_featured") VALUES (, .join(vals));
INSERT INTO "attribute" ("id", "name", "slug", "type", "image_url", "is_featured") VALUES (, .join(vals));
INSERT INTO "attribute" ("id", "name", "slug", "type", "image_url", "is_featured") VALUES (, .join(vals));
INSERT INTO "attribute" ("id", "name", "slug", "type", "image_url", "is_featured") VALUES (, .join(vals));

-- attribute_value (7 rows)
DELETE FROM "attribute_value";
INSERT INTO "attribute_value" ("id", "attribute_id", "value", "image_url") VALUES (, .join(vals));
INSERT INTO "attribute_value" ("id", "attribute_id", "value", "image_url") VALUES (, .join(vals));
INSERT INTO "attribute_value" ("id", "attribute_id", "value", "image_url") VALUES (, .join(vals));
INSERT INTO "attribute_value" ("id", "attribute_id", "value", "image_url") VALUES (, .join(vals));
INSERT INTO "attribute_value" ("id", "attribute_id", "value", "image_url") VALUES (, .join(vals));
INSERT INTO "attribute_value" ("id", "attribute_id", "value", "image_url") VALUES (, .join(vals));
INSERT INTO "attribute_value" ("id", "attribute_id", "value", "image_url") VALUES (, .join(vals));

-- brand (1 rows)
DELETE FROM "brand";
INSERT INTO "brand" ("id", "name", "logo") VALUES (, .join(vals));

-- category (14 rows)
DELETE FROM "category";
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));
INSERT INTO "category" ("id", "name", "img", "bg", "count", "parent_id", "gender") VALUES (, .join(vals));

-- contact_message (2 rows)
DELETE FROM "contact_message";
INSERT INTO "contact_message" ("id", "name", "email", "phone", "message", "date") VALUES (, .join(vals));
INSERT INTO "contact_message" ("id", "name", "email", "phone", "message", "date") VALUES (, .join(vals));

-- coupon (1 rows)
DELETE FROM "coupon";
INSERT INTO "coupon" ("id", "code", "type", "discount", "threshold", "usage_limit", "expiry_date", "is_active") VALUES (, .join(vals));

-- order (5 rows)
DELETE FROM "order";
INSERT INTO "order" ("id", "order_number", "user_id", "date", "total_amount", "status", "coupon_code", "discount_amount") VALUES (, .join(vals));
INSERT INTO "order" ("id", "order_number", "user_id", "date", "total_amount", "status", "coupon_code", "discount_amount") VALUES (, .join(vals));
INSERT INTO "order" ("id", "order_number", "user_id", "date", "total_amount", "status", "coupon_code", "discount_amount") VALUES (, .join(vals));
INSERT INTO "order" ("id", "order_number", "user_id", "date", "total_amount", "status", "coupon_code", "discount_amount") VALUES (, .join(vals));
INSERT INTO "order" ("id", "order_number", "user_id", "date", "total_amount", "status", "coupon_code", "discount_amount") VALUES (, .join(vals));

-- order_item (5 rows)
DELETE FROM "order_item";
INSERT INTO "order_item" ("id", "order_id", "product_id", "quantity", "price_at_time", "variation_id", "variation_label") VALUES (, .join(vals));
INSERT INTO "order_item" ("id", "order_id", "product_id", "quantity", "price_at_time", "variation_id", "variation_label") VALUES (, .join(vals));
INSERT INTO "order_item" ("id", "order_id", "product_id", "quantity", "price_at_time", "variation_id", "variation_label") VALUES (, .join(vals));
INSERT INTO "order_item" ("id", "order_id", "product_id", "quantity", "price_at_time", "variation_id", "variation_label") VALUES (, .join(vals));
INSERT INTO "order_item" ("id", "order_id", "product_id", "quantity", "price_at_time", "variation_id", "variation_label") VALUES (, .join(vals));

-- product (96 rows)
DELETE FROM "product";
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));
INSERT INTO "product" ("id", "name", "cat_name", "category_id", "sub_category_id", "brand_id", "price", "orig", "badge", "img", "desc", "sizes", "colors", "size_chart", "product_type", "stock_status", "is_featured", "materials", "care", "is_best_seller", "is_new_arrival", "seo_title", "seo_description", "focus_keyword", "meta_keywords", "product_tags") VALUES (, .join(vals));

-- product_attribute (91 rows)
DELETE FROM "product_attribute";
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));
INSERT INTO "product_attribute" ("id", "product_id", "attribute_id") VALUES (, .join(vals));

-- product_image (40 rows)
DELETE FROM "product_image";
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));
INSERT INTO "product_image" ("id", "product_id", "attribute_value_id", "img_url") VALUES (, .join(vals));

-- product_variation (0 rows)
DELETE FROM "product_variation";

-- review (0 rows)
DELETE FROM "review";

-- selected_attribute_value (91 rows)
DELETE FROM "selected_attribute_value";
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));
INSERT INTO "selected_attribute_value" ("id", "product_id", "attribute_id", "attribute_value_id") VALUES (, .join(vals));

-- sub_category (0 rows)
DELETE FROM "sub_category";

-- subscriber (0 rows)
DELETE FROM "subscriber";

-- user (2 rows)
DELETE FROM "user";
INSERT INTO "user" ("id", "email", "password_hash", "is_admin", "join_date", "username", "phone", "address", "city", "zipcode") VALUES (, .join(vals));
INSERT INTO "user" ("id", "email", "password_hash", "is_admin", "join_date", "username", "phone", "address", "city", "zipcode") VALUES (, .join(vals));

-- variation_option (0 rows)
DELETE FROM "variation_option";
